site_name: 'Compose Unstyled'
site_description: "Compose Unstyled is a set of foundational components for building high-quality, accessible design systems in Compose Multiplatform."
site_url: https://composeunstyled.com
docs_dir: 'docs'

repo_name: 'Compose Unstyled'
repo_url: https://github.com/composablehorizons/compose-unstyled/

theme:
  name: material
  custom_dir: docs/overrides
  favicon: assets/logo.png
  logo: assets/logo.png
  font:
    text: Fira Sans
    code: Jetbrains Mono
  features:
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: 'white'
      accent: 'gray'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: 'black'
      accent: 'gray'
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Overview:
      - Introduction: introduction.md
  - Components:
    - 'Bottom Sheet' : bottom-sheet.md
    - 'Bottom Sheet (Modal)' : modal-bottom-sheet.md
    - 'Checkbox' : checkbox.md
    - 'Dialog' : dialog.md
    - 'Dropdown (Menu)' : dropdown-menu.md
    - 'Icon' : icon.md
    - 'Progress Indicator' : progressindicator.md
    - 'Radio Group' : radiogroup.md
    - 'Scroll Area (Scrollbars)' : scrollarea.md
    - 'Separators' : separators.md
    - 'Slider' : slider.md
    - 'Tab Group' : tabgroup.md

plugins:
  - social
  - search

extra:
  analytics:
    provider: custom
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/composablehorizons/
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/alexstyl

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.betterem
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  <a href="https://github.com/composablehorizons"><img  src="/composables.svg"></a>