site_name: Compose Menu (Dropdown)
repo_url: https://github.com/composablehorizons/compose-menu/
site_url: https://composablehorizons.github.io/compose-menu/
theme:
  name: material
  font:
    text: Fira Sans
    code: Jetbrains Mono
  features:
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      primary: white
      accent: gray

plugins:
  - social
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/composablehorizons/
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/alexstyl

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.betterem
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  <a href="https://github.com/composablehorizons"><img  src="composables.svg"></a>