[versions]
compose = "1.6.2"
kotlin = "1.9.23"
composetheme = "1.2.0-alpha"

[libraries]
composetheme = { module = "com.composables:composetheme", version.ref = "composetheme" }


[plugins]
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }